# Site Configuration

title: wangjiyao
description: wangjiyao的个人展示页

lang: zh-CN
timezone: Asia/Shanghai

# Build settings
markdown: kramdown

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
